### ISSUE TITLE
Any way to use it without a dnsmasq-able router or a rpi?

### ISSUE THREAD

**Issue by shad00m** [trick77/dockerflix#8]
I got everything set up here but i'd like to share it to a couple of my friends and they dont have a router with editable dnsmasq, custom-firmware, rpi/etc available.

Is there any way that it could work?

**Comment by ghost** [comment]
I think it's possible if you also setup Dnsmasq on you VPS.
So now your VPS is acting as a DNS server(Dnsmasq) and a proxy(Sniproxy).
But be aware of the latency introduced due to changing default DNS servers.

You can read more about that from [tunlr-style-dns-unblocking](https://github.com/trick77/tunlr-style-dns-unblocking) and the linked blog posts.

**Comment by trick77** [comment]
Just don't. 
http://openresolverproject.org

That is exactly why I did not include this in dockerflix.
